### PR TITLE
updated files

### PR DESCRIPTION
**Pull request by Justme764**
PR 1  update CODE_OF_CONDUCT to code_of_conduct and changes email address. this email address  hello@lord.io to tal@dav.networ
PR 2 Add editorconfig file issue #4  did not do the below this time.  hope it worked.
did NOT do the below statement this time.

### CODE REVIEW

**Comment by Justme764** [comment]
I did both pulls in one and to the main branch.  hope I did i right this time. also just a curiosity question why is that statement on the PR?  lord/slate thanks.  can't wait to learn more.

**Comment by cg-cnu** [comment]
@Justme764 Since you fixed lot of issues in this one am closing it. Lets work on a new pr to update the code of conduct.

**Comment by Justme764** [comment]
@cg-cnu  I will do now.

**Comment by Justme764** [comment]
@cg-cnu  since I already fixed the code of conduct, how do I do a new pr for just that one?  thanks for your help.

**Pull request closed without merging**
