### PR TITLE
#7 Add license badge to readme (first-timers-only)

### PR DESCRIPTION
**Pull request by max810**
Added a MIT license badge to README.md

### CODE REVIEW

**Comment by cg-cnu** [comment]
Hey @max810 Thanks for working on it. You added the badge in a wrong place. It has to be below the title next to the gitter badge. You can have a look at the other project to get an idea, like [missions](https://github.com/davfoundation/missions#missions) 

You can just modify the local file and recommit and push it to the origin. Your pr will automatically get updated. Let me know if you need any help! 🙂

**Comment by max810** [comment]
Sorry, my bad. Fixed it.

**Comment by max810** [comment]
Oh, and there must have been a whitespace. My bad x2.

**Comment by cg-cnu** [comment]
No problem @max810 we all are learning. I just noticed it and about to mention. Thanks a ton for fixing it. Am going to merge it.

**Comment by max810** [comment]
Well, that was ... surprisingly easy. Thank you for helping newcomers and beginners like me by creating such first-timers-only issues. Thanks for your cooperation.

**Pull request merged**
